name: LsTodo

on:
  push:
    branches: [ "main" ]

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@<TAG>
        with:
          pkgname: lstodo
          pkgbuild: ./PKGBUILD