name: LsTodo


on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: KSXGitHub/github-actions-deploy-aur@v2.7.2
    - name: Build
      with:
        pkgbuild: ./PKGBUILD
